name: cd

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: Tagged Release
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Build project
        run: uv build
      - name: Deploy release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          prerelease: false
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: |
            dist/*.whl
            dist/*.tar.gz
      - name: Publish to PyPI
        run: uv publish
